#######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Backup-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
#
#######################################################################################################################
autoplug-backup-config:

  #######################################################################################################################
  # SERVER-FILES BACKUP
  #######################################################################################################################
  #Backups your server.jar and all setting files before startup to /autoplug-backups/server/...zip
  server-files-backup:
    enable: false

    #Set max-days to 0 if you want to keep your backups forever.
    max-days: 7

  #######################################################################################################################
  # WORLDS BACKUP
  #######################################################################################################################
  #Backups all folders starting with "world" to /autoplug-backups/worlds/...zip
  worlds-backup:
    enable: false

    #Set max-days to 0 if you want to keep your backups forever.
    max-days: 7

  #######################################################################################################################
  # PLUGINS BACKUP
  #######################################################################################################################
  #Backups your plugins folder before startup to /autoplug-backups/plugins/...zip
  plugins-backup:
    enable: true

    #Set max-days to 0 if you want to keep your backups forever.
    max-days: 7