#######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Check-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
#
#######################################################################################################################
autoplug-check-config:

  #######################################################################################################################
  # SERVER CHECK
  #######################################################################################################################
  #This will check for the latest server jar available, download it and replace it with the latest version before startup
  server-check:
    enable: false

    #Currently supported server software: PAPER (https://papermc.io/)
    software: PAPER

    #Currently supported server versions (always latest): 1.15.x, 1.14.x, 1.13.x, 1.12.x, 1.8.x
    version: 1.15.x

  #######################################################################################################################
  # PLUGINS CHECK
  #######################################################################################################################
  # DISCLAIMER:
  # Even though the AUTOMATIC profile is heavily tested for bugs, issues may happen!
  # We (OsirisTeam) do NOT guarantee the safety of your files and we are not responsible for any loss of data.
  # By enabling this feature, you accept the risk and you take full responsibility over your files.
  #######################################################################################################################
  plugins-check:
    enable: true

    #Select your operating profile for plugins-check: MANUAL or AUTOMATIC
    #You can exclude plugins from the check at /plugins/AutoPlugPlugin/config.yml
    profile: MANUAL
    # Features of profile MANUAL:
    # - Update-check [YES]  - Searches online (via Spiget) for plugin updates
    # - Updates-download [YES]  - Downloads the updated jar files to /plugins/autoplug-cache
    # - Delete-old [NO] - Replaces old jar files with newly downloaded ones in /plugins
    # - server-restart [NO] - Restarts the server
    #
    # Features of profile AUTOMATIC:
    # - Update-check [YES]
    # - Updates-download [YES]
    # - Delete-old [YES]
    # - server-restart [YES]

  #Toggles debug mode
  debug: false