#######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Restarter-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
#
#######################################################################################################################
autoplug-restarter-config:

  #######################################################################################################################
  # DAILY-RESTARTER
  #######################################################################################################################
  #Powerfull scheduler for restarting your minecraft server on a daily basis
  daily-restarter:
    enable: false

    #Restarts your server daily at the times below
    #You can add max 10x times to restart (hours must be within 0-23 and minutes within 0-59)
    times:
      - '23:00'
      - '11:00'

    #Executes these commands as console before restarting
    commands:
      - 'say [Server] Server is restarting...'
      - 'say [Server] Please allow up to 2min for this process to complete.'